---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: trainedmodels.serving.kubeflow.org
spec:
  group: serving.kubeflow.org
  names:
    kind: TrainedModel
    listKind: TrainedModelList
    plural: trainedmodels
    shortNames:
      - tm
    singular: trainedmodel
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.url
          name: URL
          type: string
        - jsonPath: .status.conditions[?(@.type=='Ready')].status
          name: Ready
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: TrainedModel is the Schema for the trainedmodels API
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: TrainedModelSpec defines the desired state of TrainedModel
              properties:
                inferenceService:
                  description: parent inference service to deploy to
                  type: string
                model:
                  description: Predictor model spec
                  properties:
                    framework:
                      description: 'Machine Learning <framework name> The values could be: "tensorflow","pytorch","sklearn","onnx","xgboost", "myawesomeinternalframework" etc.'
                      type: string
                    memory:
                      anyOf:
                        - type: integer
                        - type: string
                      description: Maximum memory this model will consume, this field is used to decide if a model server has enough memory to load this model.
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    storageUri:
                      description: Storage URI for the model repository
                      type: string
                  required:
                    - framework
                    - memory
                    - storageUri
                  type: object
              required:
                - inferenceService
                - model
              type: object
            status:
              description: TrainedModelStatus defines the observed state of TrainedModel
              properties:
                activeModelState:
                  default: Pending
                  description: "High level state string: Pending, Standby, Loading, Loaded, FailedToLoad"
                  enum:
                    - ""
                    - Pending
                    - Standby
                    - Loading
                    - Loaded
                    - FailedToLoad
                  type: string
                available:
                  description: Whether the predictor endpoint is available
                  type: boolean
                conditions:
                  description: Conditions the latest available observations of a resource's current state.
                  items:
                    description: "This is used for reflecting the Ready status of the resource according to the TrainedModel CRD's expected key which is: status.conditions[?(@.type=='Ready')].status"
                    properties:
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                failedCopies:
                  default: 0
                  description: How many copies of this predictor's models failed to load recently
                  type: integer
                grpcEndpoint:
                  type: string
                httpEndpoint:
                  description: Addressable endpoint for the deployed trained model This will be "static" and will not change when the model is mutated
                  type: string
                lastFailureInfo:
                  description: Details of last failure, when load of target model is failed or blocked
                  properties:
                    location:
                      description: Name of component to which the failure relates (usually Pod name)
                      type: string
                    message:
                      description: Detailed error message
                      type: string
                    modelId:
                      description: Internal ID of model, tied to specific Spec contents
                      type: string
                    reason:
                      description: High level class of failure
                      enum:
                        - ModelLoadFailed
                        - RuntimeUnhealthy
                        - NoSupportingRuntime
                        - RuntimeNotRecognized
                        - InvalidPredictorSpec
                      type: string
                    time:
                      description: Time failure occurred or was discovered
                      format: date-time
                      type: string
                  type: object
                targetModelState:
                  default: ""
                  description: ModelState enum
                  enum:
                    - ""
                    - Pending
                    - Standby
                    - Loading
                    - Loaded
                    - FailedToLoad
                  type: string
                transitionStatus:
                  default: UpToDate
                  description: Whether the available predictor endpoint reflects the current Spec or is in transition
                  enum:
                    - UpToDate
                    - InProgress
                    - BlockedByFailedLoad
                    - InvalidSpec
                  type: string
                url:
                  type: string
              required:
                - activeModelState
                - available
                - failedCopies
                - targetModelState
                - transitionStatus
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
