name: Build and Push

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: |
          ./scripts/build_devimage.sh
      - name: Build runtime image
        run: |
          BUILD_ID=$(date '+%Y%m%d')-$(git rev-parse HEAD | cut -c -5)
          IMAGE_TAG=main_${BUILD_ID}

          ./scripts/build_docker.sh --target runtime \
            --tag $IMAGE_TAG \
            --devimage kserve/modelmesh-controller-develop

      - name: Log in to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to docker hub
        run: |
          IMAGE_NAME=modelmesh-serving
          IMAGE_ID=kserve/$IMAGE_NAME
          IMAGE_VERSION=latest

          docker push $IMAGE_ID:$IMAGE_VERSION
