name: Test

on:
  pull_request:
    branches:
      - main
      - 'release-[0-9].[0-9]+*'
    paths-ignore:
      - '.github/**'
      - '.tekton/**'
      - '**.md'
      - 'docs/**'
      - 'fvt/**'
      - 'proto/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build developer image
        run: make build.develop

      - name: Run unit tests
        run: ./scripts/develop.sh make test
